### ISSUE TITLE
tracetest.py @ 1b91571540 : Naruszenie ochrony pamięci (core dumped)

### ISSUE THREAD

**Issue by mkf** [ArchieT/armpen#1]
```
(varmpen)mf@stud1:~/armpen/testscripts$ python tracetest.py e_to_the_pi_minus_pi.png
Naruszenie ochrony pamięci (core dumped)
```

Occured with 1b915715405d5889a7a903ca69a938616e22de0f

**Comment by przymusp** [comment]
pypotrace prawdopodobnie nie jest już rozwijane (ostatni update 2013) i są problemy z nową wersją libpotrace. Lepiej poszukać innej biblioteki.

Poniżej trace na testach  z pypotrace. 

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2d90666 in __pyx_pf_7potrace_8_potrace_6Bitmap_4data___set__ (__pyx_v_value=0x920190 <_Py_NoneStruct>, __pyx_v_self=0x7ffff375a998) at potrace/_potrace.c:1568
1568      ((struct __pyx_obj_7potrace_8_potrace_Bitmap *)__pyx_v_self)->po_bitmap.w = (((struct __pyx_obj_7potrace_8_potrace_Bitmap *)__pyx_v_self)->_data->dimensions[1]);
(gdb) bt
#0  0x00007ffff2d90666 in __pyx_pf_7potrace_8_potrace_6Bitmap_4data___set__ (__pyx_v_value=0x920190 <_Py_NoneStruct>, __pyx_v_self=0x7ffff375a998) at potrace/_potrace.c:1568
#1  __pyx_setprop_7potrace_8_potrace_6Bitmap_data (o=0x7ffff375a998, v=0x920190 <_Py_NoneStruct>, x=<optimized out>) at potrace/_potrace.c:6794
#2  0x00000000004a8f8b in PyObject_SetAttr ()
#3  0x00007ffff2d8da8d in __pyx_pf_7potrace_8_potrace_6Bitmap___init__ (__pyx_v_self=0x7ffff375a998, __pyx_args=0x7ffff61d4390, __pyx_kwds=0x7ffff376b280)
    at potrace/_potrace.c:1194
#4  0x00000000004f5d0b in ?? ()
#5  0x000000000052e1e6 in PyEval_EvalFrameEx ()
#6  0x000000000055c594 in PyEval_EvalCodeEx ()
#7  0x000000000052ca8d in PyEval_EvalFrameEx ()
#8  0x000000000052cf32 in PyEval_EvalFrameEx ()
#9  0x000000000055c594 in PyEval_EvalCodeEx ()
#10 0x00000000005b7392 in PyEval_EvalCode ()
#11 0x0000000000469663 in ?? ()
#12 0x00000000004699e3 in PyRun_FileExFlags ()
#13 0x0000000000469f1c in PyRun_SimpleFileExFlags ()
#14 0x000000000046ab81 in Py_Main ()
#15 0x00007ffff7817ec5 in __libc_start_main (main=0x46ac3f <main>, argc=2, argv=0x7fffffffeb38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffeb28) at libc-start.c:287
#16 0x000000000057497e in _start ()
```

**Comment by mkf** [comment]
Nie widzę innych bibliotek dających dane w tak prostym formacie... Będę jeszcze szukał, ale możliwe że nie znajdę alternatywy i będzie trzeba zrezygnować z rysowania grafiki rastrowej, ewentualnie przetwarzać ją ręcznie osobno na krzywe.
