### ISSUE TITLE
basictest.py&'fake': they don't do almost anything, 'with'-s are exiting without doing anything

### ISSUE THREAD

**Issue by mkf** [ArchieT/armpen#3]
``````
mf@VirtuLinux:~/armpen$ python basictest.py 
start blah
bye blah
``` (then there's time.sleep and I perform KeyboardInterrupt)
``````

**Comment by mkf** [comment]
Occured with f29de7f3451cabb3c20402f7b7abb507019a9a96

**Comment by mkf** [comment]
`__exit__ <type 'exceptions.AttributeError'> pos instance has no attribute 'maszyna' <traceback object at 0x7f8d69f1ea70>`

occured with 7ac99d755fb6a672505410d56283d492e1720458

**Comment by mkf** [comment]
`__exit__ <type 'exceptions.AttributeError'> pos instance has no attribute 'r' <traceback object at 0x7f060d535ab8>`

occured with 1b50c3f

**Comment by mkf** [comment]
`__exit__ <type 'exceptions.TypeError'> unsupported operand type(s) for ^: 'float' and 'int' <traceback object at 0x7f4a47526cb0>`

occured with 013fe2f

**Comment by mkf** [comment]
`__exit__ <type 'exceptions.TypeError'> a float is required <traceback object at 0x7f774c12dc68>`

occured with 7607fd6

**Comment by mkf** [comment]
```
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 22, in draw
    armpoz(self.start,ramie).przemiesc()
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 23, in __init__
    _ = self.po
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 36, in po
    def po(self): return {'phi':self.phi,'r':self.r}
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 33, in phi
    self.phival = kat(atan2(self.yval,self.xval),"rad")
TypeError: a float is required
```

Traceback thanks to commit 160e391aa7454c51a08a6d02b4e9c62003e42141

**Comment by mkf** [comment]
```
[...]rmpen/moduly/wartosci/pos.py", line 40, in x
    else: self.xval=self.r*self.phi.sin ; return self.xval
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 26, in r
    self.rval = sqrt((self.x*self.x)+(self.y*self.y))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 40, in x
    else: self.xval=self.r*self.phi.sin ; return self.xval
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 26, in r
    self.rval = sqrt((self.x*self.x)+(self.y*self.y))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 40, in x
    else: self.xval=self.r*self.phi.sin ; return self.xval
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 26, in r
    self.rval = sqrt((self.x*self.x)+(self.y*self.y))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 40, in x
    else: self.xval=self.r*self.phi.sin ; return self.xval
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 26, in r
    self.rval = sqrt((self.x*self.x)+(self.y*self.y))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 40, in x
    else: self.xval=self.r*self.phi.sin ; return self.xval
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 26, in r
    self.rval = sqrt((self.x*self.x)+(self.y*self.y))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 40, in x
    else: self.xval=self.r*self.phi.sin ; return self.xval
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 25, in r
    from math import sqrt
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

occured with 445aa2d302aeb36cd7d00955922c8c1943592010

**Comment by mkf** [comment]
```
start blah
self.xval 0.1 self.yval 0.1 {}
self.xval 0.1 self.yval 0.1 {}
self.xval None self.yval None {}
bye blah
fake.__exit__ <type 'exceptions.TypeError'> unsupported operand type(s) for *: 'int' and 'NoneType' <traceback object at 0x7f5120050c20>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 22, in draw
    armpoz(self.start,ramie).przemiesc()
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 23, in __init__
    cosalphaodr = (arm.l1/(2*self.r))+(self.r/(2*arm.l1))-(arm.l2*arm.l2/(2*self.r*arm.l1))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

occured with fadcb2f

**Comment by mkf** [comment]
```
start blah
bye blah
fake.__exit__ <type 'exceptions.AssertionError'>  <traceback object at 0x7f5c67d75c20>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 22, in draw
    armpoz(self.start,ramie).przemiesc()
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 19, in __init__
    pos.__init__(self,poz)
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 11, in __init__
    assert (self.xval is not None and self.yval is not None) or (self.phival is not None and self.rval is not None)
AssertionError
```

occured with e13e2eb

**Comment by mkf** [comment]
Exactly the same with eb057a5

**Comment by mkf** [comment]
```
mf@VirtuLinux:~/armpen$ python basictest.py
start blah
self.start {} ramie <moduly.egzemplarze.fake.fake instance at 0x7f7dbe6afef0>
bye blah
testsource.__exit__ <type 'exceptions.AssertionError'>  <traceback object at 0x7f7db317aa70>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    armpoz(self.start,ramie).przemiesc()
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 19, in __init__
    pos.__init__(self,dict(poz))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 11, in __init__
    assert (self.xval is not None and self.yval is not None) or (self.phival is not None and self.rval is not None)
AssertionError
fake.__exit__ <type 'exceptions.AssertionError'>  <traceback object at 0x7f7db317aa70>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    armpoz(self.start,ramie).przemiesc()
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 19, in __init__
    pos.__init__(self,dict(poz))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 11, in __init__
    assert (self.xval is not None and self.yval is not None) or (self.phival is not None and self.rval is not None)
AssertionError
```

occured with eb05df7

**Comment by mkf** [comment]
```
mf@VirtuLinux:~/armpen$ python basictest.py
start blah
self.start {} ramie <moduly.egzemplarze.fake.fake instance at 0x7f9a179d3e60>
bye blah
testsource.__exit__ <type 'exceptions.AssertionError'> {} <traceback object at 0x7f9a10c19b48>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 19, in __init__
    pos.__init__(self,dict(poz))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 6, in __init__
    assert (('phi' in coordict or 'theta' in coordict) and 'r' in coordict) or ('x' in coordict and 'y' in coordict),coordict
AssertionError: {}
fake.__exit__ <type 'exceptions.AssertionError'> {} <traceback object at 0x7f9a10c19b48>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 19, in __init__
    pos.__init__(self,dict(poz))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 6, in __init__
    assert (('phi' in coordict or 'theta' in coordict) and 'r' in coordict) or ('x' in coordict and 'y' in coordict),coordict
AssertionError: {}
```

occured with feaa3a3

**Comment by mkf** [comment]
```
mf@VirtuLinux:~/armpen$ python basictest.py
start blah
{}
{}
self.start {} ramie <moduly.egzemplarze.fake.fake instance at 0x7f0e9b3e3fc8>
bye blah
testsource.__exit__ <type 'exceptions.AssertionError'> {} <traceback object at 0x7f0e94629b00>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 19, in __init__
    pos.__init__(self,dict(poz))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 6, in __init__
    assert (('phi' in coordict or 'theta' in coordict) and 'r' in coordict) or ('x' in coordict and 'y' in coordict),coordict
AssertionError: {}
fake.__exit__ <type 'exceptions.AssertionError'> {} <traceback object at 0x7f0e94629b00>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 19, in __init__
    pos.__init__(self,dict(poz))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 6, in __init__
    assert (('phi' in coordict or 'theta' in coordict) and 'r' in coordict) or ('x' in coordict and 'y' in coordict),coordict
AssertionError: {}
```

occured with 69a236f

Apparently pos doesn't read the coordict correctly

**Comment by mkf** [comment]
```
mf@VirtuLinux:~/armpen$ python basictest.py
start blah
{'y': 1.1, 'x': 1}
{'y': 1.1, 'x': 1}
1 1.1 k
{}
{'y': 6.7, 'x': 1}
{'y': 6.7, 'x': 1}
1 6.7 k
{}
self.start {} ramie <moduly.egzemplarze.fake.fake instance at 0x7f8bb1631e18>
{}
{}
bye blah
testsource.__exit__ <type 'exceptions.AssertionError'> {} <traceback object at 0x7f8baa877b00>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 19, in __init__
    pos.__init__(self,dict(poz))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 10, in __init__
    assert (('phi' in coordict or 'theta' in coordict) and 'r' in coordict) or ('x' in coordict and 'y' in coordict),coordict
AssertionError: {}
fake.__exit__ <type 'exceptions.AssertionError'> {} <traceback object at 0x7f8baa877b00>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 19, in __init__
    pos.__init__(self,dict(poz))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 10, in __init__
    assert (('phi' in coordict or 'theta' in coordict) and 'r' in coordict) or ('x' in coordict and 'y' in coordict),coordict
AssertionError: {}
```

occured with ecfe97d

**Comment by mkf** [comment]
```
mf@VirtuLinux:~/armpen$ python basictest.py
start blah
{'y': 1.1, 'x': 1}
{'y': 1.1, 'x': 1}
1 1.1 k
__init__: phi,r,x,y  None None 1 1.1
{}
{'y': 6.7, 'x': 1}
{'y': 6.7, 'x': 1}
1 6.7 k
__init__: phi,r,x,y  None None 1 6.7
{}
self.start {} ramie <moduly.egzemplarze.fake.fake instance at 0x7f3e6bf31dd0>
{}
{}
bye blah
testsource.__exit__ <type 'exceptions.AssertionError'> {} <traceback object at 0x7f3e64a46ab8>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 19, in __init__
    pos.__init__(self,dict(poz))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 10, in __init__
    assert (('phi' in coordict or 'theta' in coordict) and 'r' in coordict) or ('x' in coordict and 'y' in coordict),coordict
AssertionError: {}
fake.__exit__ <type 'exceptions.AssertionError'> {} <traceback object at 0x7f3e64a46ab8>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 19, in __init__
    pos.__init__(self,dict(poz))
  File "/home/mf/armpen/moduly/wartosci/pos.py", line 10, in __init__
    assert (('phi' in coordict or 'theta' in coordict) and 'r' in coordict) or ('x' in coordict and 'y' in coordict),coordict
AssertionError: {}
<Event(1-ActiveEvent {'state': 1, 'gain': 0})>
<Event(1-ActiveEvent {'state': 2, 'gain': 0})>
^CTraceback (most recent call last):
  File "basictest.py", line 9, in <module>
    print i
  File "/home/mf/armpen/moduly/egzemplarze/fake.py", line 36, in __exit__
    for event in pygame.event.get():
KeyboardInterrupt
mf@VirtuLinux:~/armpen$ ^C
mf@VirtuLinux:~/armpen$ 
```

`pos` takes the args, but `__dict__` is still empty

occured with d7a1a54

**Comment by mkf** [comment]
Another bug causing the same issue:

```
mf@VirtuLinux:~/armpen$ python basictest.py 
start blah
{'y': 1.1, 'x': 1}
{'y': 6.7, 'x': 1}
self.start {'y': 1.1, 'x': 1} ramie <moduly.egzemplarze.fake.fake instance at 0x7f5501357ef0>
self.xval 1 self.yval 1.1 {'y': 1.1, 'x': 1}
self.xval 1 self.yval 1.1 {'y': 1.1, 'x': 1}
self.xval 1 self.yval 1.1 {'y': 1.1, 'x': 1}
bye blah
testsource.__exit__ <type 'exceptions.TypeError'> unsupported operand type(s) for *: 'int' and 'NoneType' <traceback object at 0x7f54f9e2ab48>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 23, in __init__
    cosalphaodr = (arm.l1/(2*self.r))+(self.r/(2*arm.l1))-(arm.l2*arm.l2/(2*self.r*arm.l1))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
fake.__exit__ <type 'exceptions.TypeError'> unsupported operand type(s) for *: 'int' and 'NoneType' <traceback object at 0x7f54f9e2ab48>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 23, in __init__
    cosalphaodr = (arm.l1/(2*self.r))+(self.r/(2*arm.l1))-(arm.l2*arm.l2/(2*self.r*arm.l1))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

Occured with b13d10a

**Comment by mkf** [comment]
And another one:

```
mf@VirtuLinux:~/armpen$ python basictest.py 
start blah
{'y': 1.1, 'x': 1}
{'y': 6.7, 'x': 1}
self.start {'y': 1.1, 'x': 1} ramie <moduly.egzemplarze.fake.fake instance at 0x7f2752e7bef0>
l1 26.58 l2 19.7266202091 r 1.48660687473
bye blah
testsource.__exit__ <type 'exceptions.ValueError'> math domain error <traceback object at 0x7f274794cbd8>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 26, in __init__
    self.alphaodr = arctrig(cosalphaodr,'cos')
  File "/home/mf/armpen/moduly/wartosci/kat.py", line 77, in __init__
    kat.__init__(self,atrig(val),'rad')
ValueError: math domain error
fake.__exit__ <type 'exceptions.ValueError'> math domain error <traceback object at 0x7f274794cbd8>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 26, in __init__
    self.alphaodr = arctrig(cosalphaodr,'cos')
  File "/home/mf/armpen/moduly/wartosci/kat.py", line 77, in __init__
    kat.__init__(self,atrig(val),'rad')
ValueError: math domain error
```

Occured with a0e25d5cb062ba8f8f75aed7254ca73654a25ec7

**Comment by mkf** [comment]
```
mf@VirtuLinux:~/armpen$ python basictest.py 
start blah
{'y': 1.1, 'x': 1}
{'y': 6.7, 'x': 1}
self.start {'y': 1.1, 'x': 1} ramie <moduly.egzemplarze.fake.fake instance at 0x7f0ad256bf80>
bye blah
testsource.__exit__ <type 'exceptions.AssertionError'> Za blisko! <traceback object at 0x7f0acb03ec20>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 23, in __init__
    assert arm.l1-arm.l2<poz.r, "Za blisko!"
AssertionError: Za blisko!
fake.__exit__ <type 'exceptions.AssertionError'> Za blisko! <traceback object at 0x7f0acb03ec20>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 23, in __init__
    assert arm.l1-arm.l2<poz.r, "Za blisko!"
AssertionError: Za blisko!
```

Occured with d4e395e84c4bb598dbd1d4dbe750990460f5fadc

**Comment by mkf** [comment]
```
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 31, in __init__
    self.alphaodzera=(self.phi+self.alphaodr).naplaszczyznie['katnaplaszczyznie']
  File "/home/mf/armpen/moduly/wartosci/kat.py", line 40, in naplaszczyznie
    zdiva=divmod(self.w,float(360) if self.a=="deg" else kat(360,"deg").rad if self.a=="rad" else None)
TypeError: unsupported operand type(s) for divmod(): 'float' and 'NoneType'
```

Occured with c496b800e96119c3ed2b0824b1985515cfbbc5cb

**Comment by mkf** [comment]
This is a little more serious:

```
mf@VirtuLinux:~/armpen$ python basictest.py 
start blah
{'y': 11.1, 'x': 1}
{'y': 7.7, 'x': 1}
self.start {'y': 11.1, 'x': 1} ramie <moduly.egzemplarze.fake.fake instance at 0x7f4bc8086ef0>
l1 26.58 l2 19.7266202091 r 11.1449540152
rad 2.210755042
bye blah
testsource.__exit__ <type 'exceptions.TypeError'> unsupported operand type(s) for divmod(): 'float' and 'NoneType' <traceback object at 0x7f4bc0b9bcb0>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 31, in __init__
    self.alphaodzera=(self.phi+self.alphaodr).naplaszczyznie['katnaplaszczyznie']
  File "/home/mf/armpen/moduly/wartosci/kat.py", line 42, in naplaszczyznie
    zdiva=divmod(self.w if (self.a=="deg" or self.a=="rad") else self.deg, float(360) if self.a=="deg" else kat(360,"deg").rad if self.a=="rad" else float(360))
TypeError: unsupported operand type(s) for divmod(): 'float' and 'NoneType'
fake.__exit__ <type 'exceptions.TypeError'> unsupported operand type(s) for divmod(): 'float' and 'NoneType' <traceback object at 0x7f4bc0b9bcb0>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 31, in __init__
    self.alphaodzera=(self.phi+self.alphaodr).naplaszczyznie['katnaplaszczyznie']
  File "/home/mf/armpen/moduly/wartosci/kat.py", line 42, in naplaszczyznie
    zdiva=divmod(self.w if (self.a=="deg" or self.a=="rad") else self.deg, float(360) if self.a=="deg" else kat(360,"deg").rad if self.a=="rad" else float(360))
TypeError: unsupported operand type(s) for divmod(): 'float' and 'NoneType'
```

Occured with 4b2ea52e40745565e543b57bbb973811b08c058e

**Comment by mkf** [comment]
```
mf@VirtuLinux:~/armpen$ python basictest.py 
start blah
{'y': 11.1, 'x': 1}
{'y': 7.7, 'x': 1}
self.start {'y': 11.1, 'x': 1} ramie <moduly.egzemplarze.fake.fake instance at 0x7fb48762ef80>
l1 26.58 l2 19.7266202091 r 11.1449540152
bye blah
testsource.__exit__ <type 'exceptions.AssertionError'>  <traceback object at 0x7fb4801d2050>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 29, in __init__
    assert arm.maxbeta >= self.beta >= arm.minbeta
AssertionError
fake.__exit__ <type 'exceptions.AssertionError'>  <traceback object at 0x7fb4801d2050>
Traceback (most recent call last):
  File "basictest.py", line 8, in <module>
    i.draw(arm,0.01)
  File "/home/mf/armpen/moduly/obiekty/rysowania.py", line 23, in draw
    doprzem = armpoz(self.start,ramie)
  File "/home/mf/armpen/moduly/arm/armpoz.py", line 29, in __init__
    assert arm.maxbeta >= self.beta >= arm.minbeta
AssertionError
```

Occured with 252f2fc

**Comment by mkf** [comment]
```
[...]rt {'y': 33.1, 'x': 13} ramie <moduly.egzemplarze.fake.fake instance at 0x7f41a4f0d200>
97.9
self.start {'y': 33.1, 'x': 13} ramie <moduly.egzemplarze.fake.fake instance at 0x7f41a4f0d200>
98.0
self.start {'y': 33.1, 'x': 13} ramie <moduly.egzemplarze.fake.fake instance at 0x7f41a4f0d200>
98.1
self.start {'y': 33.1, 'x': 13} ramie <moduly.egzemplarze.fake.fake instance at 0x7f41a4f0d200>
98.2
self.start {'y': 33.1, 'x': 13} ramie <moduly.egzemplarze.fake.fake instance at 0x7f41a4f0d200>
98.3
self.start {'y': 33.1, 'x': 13} ramie <moduly.egzemplarze.fake.fake instance at 0x7f41a4f0d200>
98.4
self.start {'y': 33.1, 'x': 13} ramie <moduly.egzemplarze.fake.fake instance at 0x7f41a4f0d200>
98.5
self.start {'y': 33.1, 'x': 13} ramie <moduly.egzemplarze.fake.fake instance at 0x7f41a4f0d200>
98.6
self.start {'y': 33.1, 'x': 13} ramie <moduly.egzemplarze.fake.fake instance at 0x7f41a4f0d200>
98.7
self.start {'y': 33.1, 'x': 13} ramie <moduly.egzemplarze.fake.fake instance at 0x7f41a4f0d200>
98.8
self.start {'y': 33.1, 'x': 13} ramie <moduly.egzemplarze.fake.fake instance at 0x7f41a4f0d200>
98.9
self.start {'y': 33.1, 'x': 13} ramie <moduly.egzemplarze.fake.fake instance at 0x7f41a4f0d200>
99.0
bye blah
testsource.__exit__ <type 'exceptions.RuntimeError'> maximum recursion depth exceeded while calling a Python object <traceback object at 0x7f419da20128>
fake.__exit__ <type 'exceptions.RuntimeError'> maximum recursion depth exceeded while calling a Python object <traceback object at 0x7f419da20128>
```

Occured with f59d18a
